name: 'Hello World'
description: 'Echoes Hello World'

runs:                                                                                           
  using: 'composite'
  steps:
    - shell: bash
      run: echo "Hello World"
